### PR TITLE
Compatibility fixes

### LINKED ISSUE #16: Return Enumerator for .each instead of including Enumerable
via: http://blog.arkency.com/2014/01/ruby-to-enum-for-enumerator/

### PR DESCRIPTION
**Pull request by BrianHawley**
- Don't define things that are already defined as the same thing.
- Return enumerators instead of including Enumerable.
- Alias has_key? as key?.
- Make sure freezing works in both old and new Ruby versions.

[Fixes #16]

### CODE REVIEW

File: lib/config_module/config_option.rb [hunk 1]
```diff
@@ -36,29 +49,47 @@ def method_missing name, *args, &block
...
+        name
       end
-      name
+      protected :new_ostruct_member
     end
 
     class NotFoundError < ::ConfigModule::ConfigError
       def identifier; :key; end
     end
+
```
Comment (acook) [inline lib/config_module/config_option.rb]: Feels weird to have the above error class definition in the middle of a bunch of method definitions. Maybe it should just go at the top?
